In [15]:
#Solution 1
"""a1 = np.array([[5, 15, 25],[20, 10, 15],[35, 15, 10]])

Find the following:

1) Mean of a1 and median of a1.

2) Mean and median along the axis = 0, then perform element and element multiplication on the arrays.

3) Find the standard deviation of a1."""

import numpy as np
a1 = np.array([[5, 15, 25],[20, 10, 15],[35, 15, 10]])

#1) Mean of a1 and median of a1.
a1mean=np.mean(a1)
print("The mean of the array is:", a1mean)

#2) Mean and median along the axis = 0, then perform element and element multiplication on the arrays.
a1mean0=np.mean(a1, 0)
print("The mean of the column is:", a1mean0)
a1med0=np.median(a1, 0)
print("The median of the column is:", a1med0)
print(a1mean0*a1med0)

#3) Find the standard deviation of a1
stda1=np.std(a1)
print(stda1)

The mean of the array is: 16.666666666666668
The mean of the column is: [20.         13.33333333 16.66666667]
The median of the column is: [20. 15. 15.]
[400. 200. 250.]
8.498365855987975


In [14]:
#Solution 2
"""Problem 2 -

Write the following values into a npy file

31, 91, 100, -3, 11, -7

save the file and then print the values from the file."""


a = np.array([31, 91, 100, -3, 11, -7])
np.save('da1.npy', a) 
np.load("da1.npy")

array([ 31,  91, 100,  -3,  11,  -7])

In [20]:
#Solution 3
"""Problem 3 -

If b1 = [5, 7, 15], c1 = [3, 12, -4]

1) Find element by element multiplication on b1 and c1 and print the result.

2) What operations do we have to perform on c1 so that we can do array multiplication on b1 and c1?
Perform those operations and print the output for every step.

3) On array obtained in 2, compute a boolean array that satisfies the condition that value 
is greater than 20. Print the boolean array. 
Then find the corresponding array where the condtition is True."""

b1 = np.array([5, 7, 15])
c1 = np.array([3, 12, -4])

#1) Find element by element multiplication on b1 and c1 and print the result.
print(b1*c1)

#2) What operations do we have to perform on c1 so that we can do array multiplication on b1 and c1?
"""Perform a transpose on c1 in order to do array multiplication on b1 and c1"""
#Perform those operations and print the output for every step.
c1t=c1.T
b1c1=np.dot(b1,c1t)
print(b1c1)


[ 15  84 -60]
39
