In [22]:
# Quiz 1 
# 7/25/19
# Addie Schnirel

import numpy as np

#question 3
print("Create an array with elements 10, 12, -9 and print the corresponding array. Find its shape.")
a=[10, 12, -9]
print(a)
print(np.shape(a))

#question 4
print("If array C has rows [11, -3, 5], [2, 6, 9], [20, 4, 11], then broadcast 3 to every element of C.")
C=np.array([[11, -3, 5], [2, 6, 9], [20, 4, 11]]) 
C3=C+3
print(C3)

#question 5
print("D has rows [3, 6], [7, 5], [10, 1], compute the transpose of D and perform matrix multiplication on D and D transpose.")
D=np.array([[3, 6], [7, 5], [10, 1]])
DmultD=np.dot(D,D.T)
print(DmultD)

#question 6
print("If S has rows [10, 20] and [21, 35], then check if values in S are greater than 20 and create and print an array whose elements satisfy this condition.")
S=np.array([[10, 20], [21, 35]])
S20=S[S>20]
print(S20)

#question 7
print("If array A has rows [15, 7, 8], [12, 10, 3], [6, 11, 5] find the mean and median of A.")
A =np.array([[15, 7, 8], [12, 10, 3], [6, 11, 5]])
meanA=np.mean(A)
medianA=np.median(A)
print(meanA,medianA)

Create an array with elements 10, 12, -9 and print the corresponding array. Find its shape.
[10, 12, -9]
(3,)
If array C has rows [11, -3, 5], [2, 6, 9], [20, 4, 11], then broadcast 3 to every element of C.
[[14  0  8]
 [ 5  9 12]
 [23  7 14]]
D has rows [3, 6], [7, 5], [10, 1], compute the transpose of D and perform matrix multiplication on D and D transpose.
[[ 45  51  36]
 [ 51  74  75]
 [ 36  75 101]]
If S has rows [10, 20] and [21, 35], then check if values in S are greater than 20 and create and print an array whose elements satisfy this condition.
[21 35]
If array A has rows [15, 7, 8], [12, 10, 3], [6, 11, 5] find the mean and median of A.
8.555555555555555 8.0
